/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface IOptions {
  /** Interface prefix, default value is "I" */
  prefix?: string
  /** Enum type prefix, default value is "T" */
  prefixOfEnum?: string
  /** When parse schema error, this message will be returned */
  parseErrorMessage?: string
  /** Display comments at the top of the code */
  explain?: string
  /** Whether to automatically generate comments, default value is false */
  isGenComment?: boolean
  /** Default value is 2 */
  indent?: number
  /** Enable semicolon, default value is true */
  semi?: boolean
  /** If this is enabled, it will generate the optional interface, default value is true */
  optional?: boolean
  /**
   * If you don't want to generate the type of an attribute in a root object,
   * you can pass in the key name of the corresponding attribute.
   * Like this, ignore_keys: ["firstName", "lastName"]
   * Schema2ts will ignore the two attributes and doesn't generate the type of them.
   */
  ignoreKeys?: Array<string>
}
export function schemaToTs(schema: string, options?: IOptions): string
